### ISSUE TITLE
 TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by kiruthika94** [kiruthika94/Twitter-api#2]
while calling function in main ,it shows type error .
code 
expand_url(urls)

**Comment by dbinoj** [comment]
Check Indentation:
https://github.com/kiruthika94/Twitter-api/blob/master/twitter.py#L79

**Comment by kiruthika94** [comment]
i checked.again same error

**Comment by dbinoj** [comment]
Ok. `urls` is not a string. its a list of urls. `expand_url()` expects a string.

**Comment by kiruthika94** [comment]
fixed. was expecting string and sending list
